import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { getEvent, getEventAudit, getEventSummary, getGeoClusters, getGeoHotspots, getGeoRegions, listEvents } from "../src/api/client";
import { IncidentBriefPage } from "../src/pages/IncidentBriefPage";
import { SituationPage } from "../src/pages/SituationPage";

vi.mock("../src/api/client", () => ({ getEvent: vi.fn(), getEventAudit: vi.fn(), getEventSummary: vi.fn(), getGeoClusters: vi.fn(), getGeoHotspots: vi.fn(), getGeoRegions: vi.fn(), getWeatherForecast: vi.fn().mockResolvedValue({ status: "unavailable", source: "open-meteo", forecast: null }), listEvents: vi.fn() }));
vi.mock("maplibre-gl", () => ({ default: { Map: class { addControl() { return this; } on() { return this; } remove() {} }, Marker: class { setLngLat() { return this; } setPopup() { return this; } addTo() { return this; } }, Popup: class { setText() { return this; } }, NavigationControl: class {} } }));
const event = { id: "event-1", external_id: "external-1", event_type: "FLOOD", severity: "HIGH", title: "Flood report", description: "Operational observation", raw_text: "Operational observation", latitude: 26.1, longitude: 91.7, state: "Assam", district: "Kamrup", city: "Guwahati", observed_at: "2026-09-19T06:00:00Z", received_at: "2026-09-19T06:05:00Z", created_at: "2026-09-19T06:00:00Z", updated_at: "2026-09-19T06:00:00Z", processing_status: "COMPLETE", system_assessment: "NEEDS_REVIEW", admin_status: "UNREVIEWED", version: 1, metadata: { origin_mode: "OPEN_METEO_LIVE", source_reference: "https://open-meteo.com/", connector_version: "1.0", retrieved_at: "2026-09-19T06:05:00Z" }, source: { id: "source", name: "Open-Meteo", source_type: "EXTERNAL_WEATHER", reliability: null, enabled: true } } as const;
const list = vi.mocked(listEvents); const summary = vi.mocked(getEventSummary); const detail = vi.mocked(getEvent); const audit = vi.mocked(getEventAudit);
const clusters = vi.mocked(getGeoClusters); const hotspots = vi.mocked(getGeoHotspots); const regions = vi.mocked(getGeoRegions);
clusters.mockResolvedValue([]);
hotspots.mockResolvedValue([]);
regions.mockResolvedValue([]);
function provider(page: React.ReactNode) { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}>{page}</QueryClientProvider>); }
beforeEach(() => vi.stubEnv("VITE_MAPPLS_ACCESS_TOKEN", ""));
afterEach(() => { vi.clearAllMocks(); vi.unstubAllEnvs(); });
test("time windows update URL and event query, while ALL removes the bound", async () => { summary.mockResolvedValue({ total_events: 1, by_processing_status: {}, by_system_assessment: {}, by_admin_status: {} }); list.mockResolvedValue({ items: [event], page: 1, page_size: 100, total: 1 }); provider(<MemoryRouter initialEntries={["/?window=6h"]}><SituationPage /></MemoryRouter>); expect(await screen.findByText("Operational weather picture")).toBeInTheDocument(); expect(list).toHaveBeenCalledWith(expect.objectContaining({ date_from: expect.any(String) })); fireEvent.click(screen.getByRole("button", { name: "ALL" })); await waitFor(() => expect(list).toHaveBeenLastCalledWith({ page_size: 100 })); });
test("invalid window falls back safely and selected empty window explains itself", async () => { summary.mockResolvedValue({ total_events: 0, by_processing_status: {}, by_system_assessment: {}, by_admin_status: {} }); list.mockResolvedValue({ items: [], page: 1, page_size: 100, total: 0 }); provider(<MemoryRouter initialEntries={["/?window=nope"]}><SituationPage /></MemoryRouter>); expect(await screen.findByText(/No weather events were observed/)).toBeInTheDocument(); expect(list).toHaveBeenCalledWith({ page_size: 100 }); });
test("geographic layer controls use the matching PostGIS APIs", async () => { summary.mockResolvedValue({ total_events: 1, by_processing_status: {}, by_system_assessment: {}, by_admin_status: {} }); list.mockResolvedValue({ items: [event], page: 1, page_size: 100, total: 1 }); clusters.mockResolvedValue([{ cluster_id: "cluster-1", event_ids: ["event-1"], event_count: 1, longitude: 91.7, latitude: 26.1, event_type_distribution: { FLOOD: 1 }, severity_distribution: { HIGH: 1 }, observed_from: "2026-09-19T06:00:00Z", observed_to: "2026-09-19T06:00:00Z", method: "PostGIS" }]); hotspots.mockResolvedValue([{ cell_id: "cell-1", event_ids: ["event-1"], event_count: 1, longitude: 91.7, latitude: 26.1, event_type_distribution: { FLOOD: 1 }, severity_distribution: { HIGH: 1 }, geometry: { type: "Polygon", coordinates: [[[91, 26], [92, 26], [92, 27], [91, 26]]] }, method: "PostGIS" }]); regions.mockResolvedValue([{ state: "Assam", district: "Kamrup", event_count: 1, grouping_method: "source-provided administrative attributes" }]); provider(<MemoryRouter initialEntries={["/?window=3h"]}><SituationPage /></MemoryRouter>); expect(await screen.findByText(/Grouped by source-provided location/)).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Clusters" })); await waitFor(() => expect(clusters).toHaveBeenCalledWith(expect.objectContaining({ date_from: expect.any(String) }))); fireEvent.click(screen.getByRole("button", { name: "Hotspots" })); await waitFor(() => expect(hotspots).toHaveBeenCalledWith(expect.objectContaining({ date_from: expect.any(String) }))); expect(screen.getByText(/Concentration of submitted reports/)).toBeInTheDocument(); });
test("direct incident brief renders provenance, separate statuses, audit, and print", async () => { detail.mockResolvedValue(event); audit.mockResolvedValue([{ id: "audit", event_id: "event-1", event_type: "WEATHER_EVENT", action: "VERIFY", actor_type: "HUMAN", actor_id: "operator", actor_name: "SIH Demo Operator", previous_value: "UNREVIEWED", new_value: "VERIFIED", reason: "Evidence reviewed", created_at: "2026-09-19T07:00:00Z" }]); const print = vi.spyOn(window, "print").mockImplementation(() => undefined); provider(<MemoryRouter initialEntries={["/events/event-1/brief"]}><Routes><Route path="/events/:eventId/brief" element={<IncidentBriefPage />} /></Routes></MemoryRouter>); expect(await screen.findByText("Operational Incident Brief")).toBeInTheDocument(); expect(screen.getByText("OPEN METEO LIVE")).toBeInTheDocument(); expect(screen.getByText("NEEDS_REVIEW")).toBeInTheDocument(); expect(screen.getByText("VERIFY")).toBeInTheDocument(); expect(screen.getByText(/Evidence reviewed/)).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Print / Save PDF" })); expect(print).toHaveBeenCalled(); });
test("incident brief handles missing event", async () => { detail.mockRejectedValue(new Error("missing")); audit.mockResolvedValue([]); provider(<MemoryRouter initialEntries={["/events/missing/brief"]}><Routes><Route path="/events/:eventId/brief" element={<IncidentBriefPage />} /></Routes></MemoryRouter>); expect(await screen.findByText("Incident brief unavailable.")).toBeInTheDocument(); });
