import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";

import { listEvents } from "../api/client";
import { StatusBadge } from "../components/StatusBadge";
import type { EventFilters } from "../types/events";

const categories = ["", "HEAVY_RAINFALL", "FLOOD", "THUNDERSTORM", "HEATWAVE", "FOG", "DUST_STORM", "STRONG_WIND"];

export function EventsPage() {
  const [filters, setFilters] = useState<EventFilters>({ page: 1, page_size: 10 });
  const events = useQuery({ queryKey: ["events", filters], queryFn: () => listEvents(filters) });
  const update = (key: keyof EventFilters, value: string) => setFilters((current) => ({ ...current, [key]: value || undefined, page: 1 }));
  const page = filters.page ?? 1;

  const content = events.isLoading ? <p className="empty-state">Loading event records…</p> : events.isError || !events.data ? <p className="empty-state">Unable to load events. Check the API connection and retry.</p> : events.data.items.length === 0 ? <p className="empty-state">No records match these filters.</p> : <><div className="event-table-wrap"><table><thead><tr><th>Event</th><th>Severity</th><th>Location</th><th>Processing</th><th>Assessment</th><th>Review</th></tr></thead><tbody>{events.data.items.map((event) => <tr key={event.id}><td><Link to={`/events/${event.id}`}>{event.title}</Link><small>{new Date(event.observed_at).toLocaleString()}</small></td><td>{event.severity}</td><td>{[event.city, event.state].filter(Boolean).join(", ") || "Pending"}</td><td><StatusBadge label="Processing" value={event.processing_status} /></td><td><StatusBadge label="System" value={event.system_assessment} /></td><td><StatusBadge label="Human" value={event.admin_status} /></td></tr>)}</tbody></table></div><div className="pagination"><span>{events.data.total} events</span><button disabled={page === 1} onClick={() => setFilters((current) => ({ ...current, page: page - 1 }))}>Previous</button><span>Page {page}</span><button disabled={page * (filters.page_size ?? 10) >= events.data.total} onClick={() => setFilters((current) => ({ ...current, page: page + 1 }))}>Next</button></div></>;
  return <section className="events-page"><header className="page-heading"><p className="eyebrow">Event explorer</p><h2>Weather event records</h2><p>Filter canonical reports while preserving processing, automated assessment, and human review state.</p></header><div className="filter-bar"><label>Category<select aria-label="Event category" onChange={(event) => update("event_type", event.target.value)} value={filters.event_type ?? ""}>{categories.map((category) => <option key={category} value={category}>{category ? category.replaceAll("_", " ") : "All categories"}</option>)}</select></label><label>State<input aria-label="State" onChange={(event) => update("state", event.target.value)} placeholder="Any state" value={filters.state ?? ""} /></label><label>Severity<select aria-label="Severity" onChange={(event) => update("severity", event.target.value)} value={filters.severity ?? ""}><option value="">All severities</option><option>LOW</option><option>MODERATE</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Processing<select aria-label="Processing status" onChange={(event) => update("processing_status", event.target.value)} value={filters.processing_status ?? ""}><option value="">All processing</option><option>COMPLETE</option><option>PARTIAL</option><option>FAILED</option></select></label><label>Assessment<select aria-label="System assessment" onChange={(event) => update("system_assessment", event.target.value)} value={filters.system_assessment ?? ""}><option value="">All assessments</option><option>PENDING</option><option>NEEDS_REVIEW</option><option>UNAVAILABLE</option><option>CORROBORATED</option><option>DISPUTED</option></select></label><label>Review<select aria-label="Human review status" onChange={(event) => update("admin_status", event.target.value)} value={filters.admin_status ?? ""}><option value="">All review states</option><option>UNREVIEWED</option><option>VERIFIED</option><option>REJECTED</option><option>ESCALATED</option></select></label></div>{content}</section>;
}
