import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";

import { getEvent, getEventAudit } from "../api/client";
import { AuditTimeline } from "../components/AuditTimeline";

export function IncidentBriefPage() {
  const { eventId = "" } = useParams();
  const event = useQuery({ queryKey: ["event", eventId], queryFn: () => getEvent(eventId) });
  const audit = useQuery({ queryKey: ["event-audit", eventId], queryFn: () => getEventAudit(eventId) });
  if (event.isLoading) return <p className="empty-state">Preparing incident brief…</p>;
  if (event.isError || !event.data) return <p className="empty-state">Incident brief unavailable.</p>;
  const item = event.data;
  const origin = String(item.metadata.origin_mode ?? (item.metadata.demo_fixture ? "DEMO_FIXTURE" : "CITIZEN_REPORT"));
  const retrievedAt = typeof item.metadata.retrieved_at === "string" ? item.metadata.retrieved_at : null;
  const cacheAge = typeof item.metadata.cache_age_seconds === "number" ? item.metadata.cache_age_seconds : null;
  const machineAnalysis = item.metadata.machine_analysis as { verification?: { evidence?: { score?: number; coverage?: number; components?: Array<{ name: string; available: boolean; weighted_contribution: number; reason_codes?: string[] }> } } } | undefined;
  const evidence = machineAnalysis?.verification?.evidence;
  const row = (label: string, value: string) => <div><dt>{label}</dt><dd>{value}</dd></div>;
  return <article className="incident-brief"><header><p className="eyebrow">WeatherFusion India</p><h1>Operational Incident Brief</h1><p>Report {item.id} · Generated {new Date().toLocaleString()}</p><button className="print-action" onClick={() => window.print()}>Print / Save PDF</button><Link to={`/events/${item.id}`}>Return to event</Link></header><section><h2>Event summary</h2><dl>{row("Event type", item.event_type.replaceAll("_", " "))}{row("Severity", item.severity)}{row("Title", item.title)}{row("Location", [item.city, item.district, item.state].filter(Boolean).join(", ") || "Not recorded")}{row("Coordinates", item.latitude === null ? "Not recorded" : `${item.latitude}, ${item.longitude}`)}{row("Observed", new Date(item.observed_at).toLocaleString())}{row("Received", new Date(item.received_at).toLocaleString())}</dl></section><section><h2>Source & provenance</h2><dl>{row("Source", item.source.name)}{row("Source type", item.source.source_type)}{row("Origin", origin.replaceAll("_", " "))}{origin === "OPEN_METEO_CACHED" && row("Data status", "Cached / stale external observation")}{row("External record", item.external_id || "Not recorded")}{row("Source reference", String(item.metadata.source_reference ?? "Not recorded"))}{retrievedAt && row("Retrieved", new Date(retrievedAt).toLocaleString())}{cacheAge !== null && row("Cache age", `${Math.round(cacheAge / 60)} minutes`)}{row("Connector version", String(item.metadata.connector_version ?? "Not recorded"))}</dl></section><section><h2>Media evidence</h2>{item.media_evidence?.length ? <ul>{item.media_evidence.map((media) => <li key={media.id}>{media.media_type} — {media.source_name} — {media.reference}</li>)}</ul> : <p>No media evidence recorded.</p>}</section><section><h2>System assessment</h2><dl>{row("Processing", item.processing_status)}{row("System assessment", item.system_assessment)}{row("Human review", item.admin_status)}{evidence ? row("Evidence support score", `${Math.round((evidence.score ?? 0) * 100)}% (${Math.round((evidence.coverage ?? 0) * 100)}% evidence coverage)`) : row("Evidence support score", "Unavailable — no evidence channels contributed")}</dl>{evidence?.components?.length ? <ul>{evidence.components.map((component) => <li key={component.name}>{component.name}: {component.available ? `${Math.round(component.weighted_contribution * 100)}% contribution` : "unavailable"}{component.reason_codes?.length ? ` (${component.reason_codes.join(", ")})` : ""}</li>)}</ul> : null}<p>The evidence score ranks available supporting evidence under the prototype policy. It does not prove a report true; human review remains authoritative.</p></section><section><h2>Audit timeline</h2>{audit.data ? <AuditTimeline entries={audit.data} /> : <p>Human review: Pending</p>}</section><footer>This brief is generated from WeatherFusion India operational data and recorded source provenance. Automated system assessments are decision-support signals and do not replace human verification.</footer></article>;
}
